// Code generated by protoc-gen-go. DO NOT EDIT.
// source: car.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Car struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Year                 int64    `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Car) Reset()         { *m = Car{} }
func (m *Car) String() string { return proto.CompactTextString(m) }
func (*Car) ProtoMessage()    {}
func (*Car) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8b9800c53a1ba42, []int{0}
}

func (m *Car) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Car.Unmarshal(m, b)
}
func (m *Car) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Car.Marshal(b, m, deterministic)
}
func (m *Car) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Car.Merge(m, src)
}
func (m *Car) XXX_Size() int {
	return xxx_messageInfo_Car.Size(m)
}
func (m *Car) XXX_DiscardUnknown() {
	xxx_messageInfo_Car.DiscardUnknown(m)
}

var xxx_messageInfo_Car proto.InternalMessageInfo

func (m *Car) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Car) GetYear() int64 {
	if m != nil {
		return m.Year
	}
	return 0
}

type CarRequest struct {
	Year                 int64    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CarRequest) Reset()         { *m = CarRequest{} }
func (m *CarRequest) String() string { return proto.CompactTextString(m) }
func (*CarRequest) ProtoMessage()    {}
func (*CarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8b9800c53a1ba42, []int{1}
}

func (m *CarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarRequest.Unmarshal(m, b)
}
func (m *CarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarRequest.Marshal(b, m, deterministic)
}
func (m *CarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarRequest.Merge(m, src)
}
func (m *CarRequest) XXX_Size() int {
	return xxx_messageInfo_CarRequest.Size(m)
}
func (m *CarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CarRequest proto.InternalMessageInfo

func (m *CarRequest) GetYear() int64 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *CarRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type CarResponse struct {
	List                 []*Car   `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CarResponse) Reset()         { *m = CarResponse{} }
func (m *CarResponse) String() string { return proto.CompactTextString(m) }
func (*CarResponse) ProtoMessage()    {}
func (*CarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8b9800c53a1ba42, []int{2}
}

func (m *CarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarResponse.Unmarshal(m, b)
}
func (m *CarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarResponse.Marshal(b, m, deterministic)
}
func (m *CarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarResponse.Merge(m, src)
}
func (m *CarResponse) XXX_Size() int {
	return xxx_messageInfo_CarResponse.Size(m)
}
func (m *CarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CarResponse proto.InternalMessageInfo

func (m *CarResponse) GetList() []*Car {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Car)(nil), "proto.Car")
	proto.RegisterType((*CarRequest)(nil), "proto.CarRequest")
	proto.RegisterType((*CarResponse)(nil), "proto.CarResponse")
}

func init() { proto.RegisterFile("car.proto", fileDescriptor_f8b9800c53a1ba42) }

var fileDescriptor_f8b9800c53a1ba42 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xb1, 0xae, 0x82, 0x30,
	0x14, 0x86, 0x6f, 0x2f, 0x70, 0x6f, 0x38, 0xc4, 0xc1, 0x13, 0x07, 0xe2, 0x60, 0x48, 0x27, 0x16,
	0x18, 0x30, 0xf1, 0x05, 0x3a, 0xb8, 0x38, 0xf5, 0x0d, 0x2a, 0xe9, 0xd0, 0xa4, 0x52, 0x6c, 0x8f,
	0x03, 0x6f, 0x6f, 0x68, 0x13, 0x65, 0xea, 0xdf, 0x2f, 0xdf, 0x9f, 0xf3, 0x43, 0x39, 0x2a, 0xdf,
	0xcf, 0xde, 0x91, 0xc3, 0x22, 0x3e, 0xbc, 0x83, 0x4c, 0x28, 0x8f, 0x08, 0x39, 0x2d, 0xb3, 0xae,
	0x59, 0xc3, 0xda, 0x52, 0xc6, 0xbc, 0xb2, 0x45, 0x2b, 0x5f, 0xff, 0x36, 0xac, 0xcd, 0x64, 0xcc,
	0xfc, 0x02, 0x20, 0x94, 0x97, 0xfa, 0xf9, 0xd2, 0x81, 0x3e, 0x06, 0xfb, 0x1a, 0x78, 0x80, 0xc2,
	0x9a, 0x87, 0xa1, 0x58, 0x2b, 0x64, 0xfa, 0xf0, 0x0e, 0xaa, 0xd8, 0x0b, 0xb3, 0x9b, 0x82, 0xc6,
	0x13, 0xe4, 0xd6, 0x04, 0xaa, 0x59, 0x93, 0xb5, 0xd5, 0x00, 0x69, 0x52, 0xbf, 0x1a, 0x91, 0x0f,
	0x02, 0x76, 0x42, 0x79, 0xe1, 0xac, 0xd5, 0x23, 0x19, 0x37, 0xe1, 0x00, 0xff, 0x57, 0x4d, 0x37,
	0x13, 0x08, 0xf7, 0x1b, 0x3b, 0xed, 0x38, 0xe2, 0x16, 0xa5, 0x13, 0xfc, 0xe7, 0xfe, 0x17, 0xe1,
	0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x65, 0xf0, 0xe6, 0xf8, 0xf5, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CarCollectionClient is the client API for CarCollection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CarCollectionClient interface {
	GetList(ctx context.Context, in *CarRequest, opts ...grpc.CallOption) (*CarResponse, error)
}

type carCollectionClient struct {
	cc *grpc.ClientConn
}

func NewCarCollectionClient(cc *grpc.ClientConn) CarCollectionClient {
	return &carCollectionClient{cc}
}

func (c *carCollectionClient) GetList(ctx context.Context, in *CarRequest, opts ...grpc.CallOption) (*CarResponse, error) {
	out := new(CarResponse)
	err := c.cc.Invoke(ctx, "/proto.CarCollection/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarCollectionServer is the server API for CarCollection service.
type CarCollectionServer interface {
	GetList(context.Context, *CarRequest) (*CarResponse, error)
}

func RegisterCarCollectionServer(s *grpc.Server, srv CarCollectionServer) {
	s.RegisterService(&_CarCollection_serviceDesc, srv)
}

func _CarCollection_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarCollectionServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CarCollection/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarCollectionServer).GetList(ctx, req.(*CarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CarCollection_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CarCollection",
	HandlerType: (*CarCollectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _CarCollection_GetList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "car.proto",
}
